title:   Veronica de Anta Felipe
logo: "/images/VeroDAF.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Analytical, energetic, and detail-oriented professional with a passion for data and technology. Skilled in the provision of strategic insight and interpretation of data, analysis of results and production of comprehensive reports. Creative in finding solutions to problems and determining modifications for optimal use of organizational data. Experienced in driving efficient and commercially focused performance reporting, I excel in developing key business intelligence and providing valuable insights to support decision-making. Strong IT skills, coupled with excellent communication abilities, enable me to effectively communicate with stakeholders and drive operational efficiencies. Seeking an opportunity to leverage my expertise and contribute to the success of a dynamic organization.
  <br><br>
   <br><br>
    <br><br>
  <a href="http://linkedin.com/in/veronicaaf">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/veronica.de.anta.felipe">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/veronicadaf/Portfolio-Veronica-de-Anta-Felipe-60ad96b8d7924dd0975427009fe80a97">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
