title:   Veronica de Anta Felipe
logo: "/images/VeroDAF.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
Experienced and passionate data and technology professional who is analytical, energetic, and detail-oriented. Skilled in providing strategic insights, interpreting data, and generating comprehensive reports. Creative problem-solver with a track record of driving efficient and commercially focused performance reporting. Excels in developing business intelligence and offering valuable insights to support decision-making. Possesses strong IT skills and excellent communication abilities to effectively engage with stakeholders and enhance operational efficiencies. Seeking to leverage expertise and contribute to a dynamic organization's success.  <br><br>
   <br><br>
    <br><br>
  <a href="http://linkedin.com/in/veronicaaf">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/veronica.de.anta.felipe">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/veronicadaf/Portfolio-Veronica-de-Anta-Felipe-60ad96b8d7924dd0975427009fe80a97">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
